export default {
  login: "ShahzaibNaeem",
  id: 105801721,
  node_id: "U_kgDOBk5n-Q",
  avatar_url: "https://avatars.githubusercontent.com/u/105801721?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ShahzaibNaeem",
  html_url: "https://github.com/ShahzaibNaeem",
  followers_url: "https://api.github.com/users/ShahzaibNaeem/followers",
  following_url:
    "https://api.github.com/users/ShahzaibNaeem/following{/other_user}",
  gists_url: "https://api.github.com/users/ShahzaibNaeem/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ShahzaibNaeem/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ShahzaibNaeem/subscriptions",
  organizations_url: "https://api.github.com/users/ShahzaibNaeem/orgs",
  repos_url: "https://api.github.com/users/ShahzaibNaeem/repos",
  events_url: "https://api.github.com/users/ShahzaibNaeem/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ShahzaibNaeem/received_events",
  type: "User",
  site_admin: false,
  name: "Shahzaib Naeem",
  company: "RagerZ",
  blog: "shahzaibblog.netlify.app",
  location: "Creil, France",
  email: null,
  hireable: null,
  bio: "Software Developer",
  twitter_username: null,
  public_repos: 13,
  public_gists: 8,
  followers: 10,
  following: 15,
  created_at: "2022-05-18T14:27:21Z",
  updated_at: "2023-05-05T10:29:58Z",
};
